### PR TITLE
Template review

### PR DESCRIPTION
**Pull request by anselmdk**
I've started out with reviewing the built-in templates a little bit. Eventually I'd like to get them in a shape where I'll have to customise as little as possible for starting out on a new shop.
For now I've just converted indentation (they were appr. 50% with spaces and 50% with tabs, so I decided to go with spaces, as `.editorconfig` file dictates), and added 2 minor features.

### CODE REVIEW

**Comment by markguinn** [comment]
These look good to me, Anselm. Are you going to commit more to this or is it ready to merge?

**Comment by oetiker** [comment]
while you are at it, you may want to change the `<i class="icon ..."` instances to `<i class="fa` to make them work with current fontawesome.

**Comment by anselmdk** [comment]
Okay, I ran into a conflict because of the indentation, sorry this has gotten so messy.
@oetiker what about opening a new issue to discuss font awesome? I think this might be a good idea, but on the other hand I like keeping the core template as library agnostic as possible.

**Comment by anselmdk** [comment]
@markguinn I'll probably work more on it over the next weeks, just wanted to get this one merged as indentation changes can cause all sorts of merge conflicts. I'm working on a project where I'll try to use the base templates as much as possible, and add styling and grid structure to them through Sass mixins (I'm using Foundation). Seems to work pretty well so far.

**Comment by bummzack** [comment]
@anselmdk Thanks for your work on this. Please squash your commits the next time (you can do this directly on github, see [here](https://github.com/blog/2141-squash-your-commits)). It keeps the git history nice and clean. Cheers

**Comment by anselmdk** [comment]
@bummzack yeah, I'll certainly do this, I'm so embarrassed about the history mess I produced...

**Pull request merged**
