### PR TITLE
Test SilverShop 2.x / SS3.7 with PHP7.1

### PR DESCRIPTION
**Pull request by wernerkrauss**

### CODE REVIEW

**Comment by bummzack** [comment]
Good idea. What about 7.2? Isn't that more important than the change from 7.0 to 7.1?

**Comment by wernerkrauss** [comment]
I tried 7.2 locally but it broke due to PHPUnit3. Let's test if it works on travis ;)

**Comment by bummzack** [comment]
Ah yes. I remember that I tried that at some point as well… didn't work on travis either :(

**Comment by wernerkrauss** [comment]
Ping, I removed my latest commit, so everything is green now.

**Comment by bummzack** [comment]
Thank you!

**Pull request merged**
