### PR TITLE
Migrate to using beforeUpdateCMSFields (Fixes #609)

### LINKED ISSUE #609: Product getCMSFields should not call the `updateCMSFields` extension hook
… Product fields should be added via `beforeUpdateCMSFields` instead.

### PR DESCRIPTION
**Pull request by wilr**

### CODE REVIEW

**Comment by wilr** [comment]
Hmm looks like my branch wasn't rebased on master. 2 secs

**Comment by bummzack** [comment]
Looking good. I think the error we're getting from tests is because of a framework error https://github.com/silverstripe/silverstripe-framework/pull/5655.
I'll update the travis config to use SilverStripe 3.6 and PHP 7 instead of 3.5 and PHP 5.6 and rerun the tests.

**Comment by bummzack** [comment]
Hm, I guess you'd have to update the `.travis.yml` file with your PR for this to work :)

Here's what I suggest:
```yml
language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - DB=MYSQL CORE_RELEASE=3.2

matrix:
  include:
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.2 COVERAGE=1
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.2 COVERAGE=2
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=3.2 COVERAGE=3
    - php: 7.0
      env: DB=PGSQL CORE_RELEASE=3.6
    - php: 5.5
      env: DB=SQLITE CORE_RELEASE=3.1
    - php: 5.6
      env: DB=PGSQL CORE_RELEASE=master
  allow_failures:
    - env: DB=PGSQL CORE_RELEASE=master

before_script:
  - composer self-update
  - phpenv rehash
  - tar cf ~/gitbackup.tar .git
  - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
  - cd ~/builds/ss

script: ./silvershop/tests/travis/run_build.sh

after_success: ./silvershop/tests/travis/upload_coverage.sh

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/a3720004986a0f249abc'
    on_success: change
    on_failure: always
    on_start: false
```

**Comment by bummzack** [comment]
Travis issues were fixed with #611. The `beforecmsfields` branch can be deleted…

**Pull request merged**
