### PR TITLE
Validate shop account form

### PR DESCRIPTION
**Pull request by adrian-stein**

### CODE REVIEW

**Comment by bummzack** [comment]
It seems like you somehow merged validation from `ShopAccountFormValidator` directly into the submit function. Having a proper validator would be more useful in my opinion though.
I've fixed Member_Validator in the silverstripe core (https://github.com/silverstripe/silverstripe-framework/pull/5098), so all this will probably obsolete once it lands (most likely in 3.4).

**Comment by adrian-stein** [comment]
I dont think the validator even being used. If it is there it should really be used.

**Comment by bummzack** [comment]
Oh, just minor improvements. Updating the query (`DataObject::get_one('Member', "$field = '$uid' AND ID != " . $currentmember->ID)`) to more recent syntax and not use `sprintf` for translation output. Although the latter is already changed in the 2.0 branch. I think in terms of functionality, the validator does what it should. Maybe a hook for extensions could be added, but not really mandatory since this should all be solved via silverstripe framework soon.

**Comment by adrian-stein** [comment]
Sounds good.

**Comment by bummzack** [comment]
Fixed via #459

**Pull request closed without merging**
