### PR TITLE
SS 4.3 compatibility: remove SearchContext from OrdersAdmin::getList()

### PR DESCRIPTION
**Pull request by xini**

### CODE REVIEW

**Comment by wilr** [comment]
Looks like a bunch of whitespace changes?

**Comment by xini** [comment]
Sorry for that, my editor must have "cleaned up"... do you want me to revert these?

**Comment by xini** [comment]
Hey @wilr, can you let me know if you want me to revert the whitepsace changes? cheers.

**Comment by wilr** [comment]
@xini What the the reasoning for removing SearchContext? Technically an API change right? Is the filtering not used at all? Whitespace changes are fine as long as it's following the `.editorconfig` format provided.

**Comment by xini** [comment]
@wilr the SearchContext doesnt work anymore.

**Comment by wilr** [comment]
Didn't see that this got deprecated!

**Comment by xini** [comment]
thanks!

**Comment by xini** [comment]
@wilr Could you please tag a release with this?

**Pull request merged**
