### PR TITLE
fix resolving of index template for stepped checkout

### PR DESCRIPTION
**Pull request by xini**

### CODE REVIEW

**Comment by wilr** [comment]
Should be fixed in 06a496c

**Comment by xini** [comment]
Hey @wilr, 06a496c only fixes this for the membership step as the first step. I would like to fix this for any first step. Thoughts?

**Comment by wilr** [comment]
Ah! Rebase this one and I'll merge then!

**Comment by xini** [comment]
Thanks. This is now rebased.

**Comment by wilr** [comment]
Looks like I can't reopen a PR on this branch.

**Comment by xini** [comment]
see #702

**Pull request closed without merging**
