### PR TITLE
[WIP] First cut of SS4 support

### LINKED ISSUE #623: SilverStripe 4 support?
It'd be great to get a SilverStripe 4-compatbile version of this going – we'd like to use it in demo pitches and we're basing all of those on SilverStripe 4 these days.

In my view, it would be better to get a version that operates the same but works in SilverStripe 4, rather than expanding the project with too many other refactoring / new feature ideas, but it would be good to hear other views on that too.

## Tasks

 * [x] Complete https://github.com/silvershop/silverstripe-listsorter/issues/14 (needed for ProductCategory)
 * [x] Complete https://github.com/burnbright/silverstripe-sqlquerylist/issues/6 (needed for ShopPeriodReport)
 * [x] Run updater script
 * [x] Run phpcbf to convert to PSR2 styleguide (if not already)
 * [x] Fix issues reported by `phpcs` 
 * [x] Add namespaces to code
 * [x] Move into PSR-4 compatible filenames / folders, add PSR-4 metadata to composer.json
 * [x] Make "silverstripe-vendormodule"
 * [x] Update all translations locally
 * [x] Push translations to transifex
 * [x] Update documentation
 * [x] Change Icons so that they fit into the SS4 CMS

### PR DESCRIPTION
**Pull request by sminnee**
Fixes #623 

This is still a work-in-progress but feel free to contribute to it!

### CODE REVIEW

**Comment by bummzack** [comment]
I picked this up and I'm working on this now. @sminnee how can I add to your PR? Can I push to your fork? Never done that before

**Comment by bummzack** [comment]
Ah yeah… pushing to the fork works. This is still very much in progress… _so much code_ 😓

**Comment by sminnee** [comment]
Great to see progress on this — sorry for the lack of reply, I was on leave. Ideally I'll have another go with this on our hackday on 16 Feb.

**Comment by bummzack** [comment]
@sminnee Welcome back. I hope to be done by then 😃

**Comment by hpeide** [comment]
Is there a branch of this some place? Maybe I can help, at least do som bugfixes.

**Comment by bummzack** [comment]
@hpeide Branch is on sminnee's fork. I pushed all my current work onto the branch right now… mostly unit-tests need fixing. Plus there's a plethora of smaller stuff that needs to be done, such as upgrading the icons to look good in SS4, fixing/namespacing the translation keys, update documentation, etc. But I'd rather fix the core parts and get unit-tests running first, then review/merge the stuff and do the other fixes later.

There are also some third-party modules that need to be upgraded to SS4, such as:

- https://github.com/markguinn/silverstripe-email-helpers
- https://github.com/markguinn/silverstripe-shop-ajax/
- https://github.com/silvershop/silvershop-shipping
- https://github.com/silvershop/silvershop-discounts
- https://github.com/silvershop/silvershop-coloredvariations
- https://github.com/silvershop/silvershop-geocoding
- https://github.com/silvershop/silvershop-stock

This one needs to change the Namespace from `Silvershop` to `SilverShop`: https://github.com/silvershop/silverstripe-hasonefield

**Comment by bummzack** [comment]
@hpeide Any help would be greatly appreciated! Feel free to tackle any task you like. ❤️

**Comment by wilr** [comment]
@bummzack I've just pushed upgrade for `silvershop-stock` and `silvershop-discounts` in progress this week. Tests won't really work I guess till this is merged back. Could we perhaps merge sminnee's branch to master, mark is as alpha in the readme or something. Happy to contribute fixes to shop core as I come across them.

**Comment by bummzack** [comment]
@wilr I'd really love to fix the unit-tests first, but there's something really weird going on with custom dataobjects (also see the #testing channel on slack)… If I can't get to the bottom of it soon, I guess I'll merge anyway

**Comment by bummzack** [comment]
I'm merging this now. There seems to be an issue with Postgres, but I'll investigate this later on. I think merging has higher priority, so that other modules can start working with `^3@dev`…

I wouldn't tag an alpha release just yet. I want to fix the postgres error and properly go through all translation-strings first. Also `phpcs` gives me tons of errors I should fix…

Then there's also a _lot_ of documentation to update.

**Pull request merged**
