### PR TITLE
introducing task ShopEmailPreviewTask

### PR DESCRIPTION
**Pull request by anselmdk**
Helper task for styling emails, see discussion [here](https://gitter.im/silvershop/silvershop-core?at=57ed671f34a8d5681ccb5cdb).

### CODE REVIEW

**Comment by anselmdk** [comment]
I'm happy to clean/pretty this up a little, if we decide for it to go into core.

**Comment by bummzack** [comment]
Looks good. If you think it's working fine, please merge (you can choose the squash option to reduce your commits to one).
Polish can be done with later PRs if necessary…

**Comment by bummzack** [comment]
Thanks for your work on this

**Comment by anselmdk** [comment]
Happy you like it. It helped me working on styling emails tonight.

**Pull request merged**
