### PR TITLE
Added a config hook to use a custom notifier

### PR DESCRIPTION
**Pull request by catharsisjelly**
Looking to supply a solution for #569, also fixed a small bit of documentation

### CODE REVIEW

**Comment by bummzack** [comment]
This PR is unnecessary, since `OrderEmailNotifier::create`, already calls:

    return Injector::inst()->create('OrderEmailNotifier', $order);

**Comment by catharsisjelly** [comment]
I'm still learning SS so trying to understand the best way to do this, would it be better to use the `->extend`?

**Comment by bummzack** [comment]
Where and how would you use `->extend`?

**Comment by catharsisjelly** [comment]
Obviously not re our conversation :) Hows this for a docs change?

**Comment by bummzack** [comment]
Great addition, thanks.

**Pull request merged**
