### PR TITLE
Added default order styling back to OrderReceiptStyle.ss for emails

### PR DESCRIPTION
**Pull request by AntonyThorpe**
Tested with both SmtpMailer and EmogrifiedSmtpMailer classes of Silverstripe Email Helpers module.  Thanks.

### CODE REVIEW

**Comment by bummzack** [comment]
@markguinn Has this been merged into 2.0 as well? Emails in 2.0 look really bleak right now.

**Comment by markguinn** [comment]
I don't remember if I did merge it or not. I may have merged it locally and forgot to push.

**Comment by markguinn** [comment]
That's exactly what happened. Fixed now.

**Comment by bummzack** [comment]
Thanks a lot!

**Pull request merged**
